RaspredInvest/RaspredInvest/urls.py
import os

from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.main, name='main'),
    path('faq/', views.faq, name='faq'),
    path('distribution/', include('appinvest.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path("signup/", include('registration.urls')),
    path('gosha/', views.gosha, name='gosha')
]

urlpatterns += static('/media/Result Files', document_root=os.path.join(settings.BASE_DIR, 'media/Result Files/'))

RaspredInvest/appinvest/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'appinvest'

urlpatterns = [
    path('', views.appdistrib, name='appdistrib'),
    path('history/', views.history, name='history'),
    path('history/<int:id>/',views.detail, name = 'detail'),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root = settings.MEDIA_ROOT
    )

RaspredInvest/registration/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path("", views.RegisterUser.as_view(), name="signup"),
]

RaspredInvest/appinvest/models.py
from django.db import models


class Result(models.Model):
    title = models.CharField('Дата результата', max_length=200, default='')
    result = models.TextField('Результат')
    table = models.TextField('Таблица')
    username = models.CharField('Имя пользователя', max_length=200, default='')
# Create your models here.

RaspredInvest/RaspredInvest/views.py
import json
import os

from django.http import HttpResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt


def main(request):
    return render(request, 'mainpage.html')


def faq(request):
    return render(request, 'faq.html')


@csrf_exempt
def gosha(request):
    if request.method == 'GET':
        return render(request,'gosha.html')

    elif request.method == 'POST':
        with open('templates/gosha.html', 'w') as file:
            file.write(request.body.decode('UTF-8'))
        return render(request,'gosha.html')

RaspredInvest/appinvest/views.py
import datetime

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, Http404
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from . import models
from .models import Result
import docx


def chunk_based_on_size(lst, n):
    for x in range(0, len(lst), n):
        each_chunk = lst[x: n+x]

        if len(each_chunk) < n:
            each_chunk = each_chunk + [None for y in range(n-len(each_chunk))]
        yield each_chunk


@login_required
@csrf_exempt
def appdistrib(request):
    if request.method == 'GET':
        return render(request, 'appdistrib.html')

    elif request.method == 'POST':
        result = request.POST.get('result')
        table = request.POST.get('out_arr')
        print(result)
        print(table)
        newrec = models.Result(
            title='Решение от ' + '.'.join(str(datetime.datetime.now()).split('.')[:-1]),
            result=result,
            table=table,
            username=str(request.user.username)
        )
        newrec.save()
        return redirect('/distribution/history')
    else:
        return HttpResponse('Что-то пошло не так..')


@login_required
def history(request):
    latest_text_list = Result.objects.filter(username=str(request.user.username)).order_by('-id')
    return render(request, 'history.html', {'latest_text_list': latest_text_list})


@csrf_exempt
@login_required
def detail(request, id):
    if request.method == 'GET':
        try:
            a = Result.objects.get(id=id)
        except:
            raise Http404('Запись не найдена!')
        if a.username == request.user.username:
            result_list = a.result.split()
            table_list = a.table.split()
            Predpriyat = result_list[1]
            name_list = []
            distib_list = []
            for i in range(int(Predpriyat)):
                name_list.append(result_list[10 + (i * 4)])
                distib_list.append(result_list[12 + (i * 4)])
            new_table_list = list(chunk_based_on_size(table_list,int(Predpriyat)))
            print(new_table_list)
            return render(request, 'detail.html', {'new_table_list': new_table_list,'text': a, 'name_list': name_list, 'distib_list': distib_list})
        else:
            return HttpResponse('Запись не найдена')

    elif (request.method == "POST") and ('Удалить' in request.POST):
        a = Result.objects.get(id=id)
        a.delete()
        return redirect('/distribution/history')

    elif (request.method == "POST") and ('Сохранить в Word' in request.POST):
        a = Result.objects.get(id=id)
        doc = docx.Document()
        doc.add_paragraph(a.result)
        doc.add_paragraph('Таблица:')
        doc.add_paragraph(a.table)
        doc.save('media/Result Files/' + a.title + '_' + str(a.id) + '.docx')
        return redirect('/media/Result Files/' + a.title + '_' + str(a.id) + '.docx')

RaspredInvest/templates/appdistrib.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

<table>
<tr>
    <td>
        <h5>Количество предприятий:</h5>
        <input required placeholder="3" value="3" size="10" id='users2' />
    </td>
    <td>
        <br>
        <p>- от 1 до 15 предприятий</p>
    </td>
</tr>
<tr>
    <td>
        <h5 >Количество капиталовложений:</h5>
        <input   size="10" placeholder="5" value="5" id='users' />
    </td>
    <td>
        <br>
        <p>- не более 15</p>
    </td>
</tr>
<tr>
    <td>
        <h5>Размер капитала:</h5>
        <input   size="10" placeholder="1000" value="1000"  id='users3' /><br><br>
    </td>
    <td>
        <br>
        <p>- не меньше количества капиталовложений, условные единицы</p>
    </td>
</tr>
</table>

<input type="button" class="btn btn-danger" id="but" value="Создать таблицу" onclick="start()" >

<script src="{% static 'js/scripts.js' %}"></script>
{% endblock %}

RaspredInvest/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">

<head>
        <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device=width,user-scalable=no, initial-scale=1.0, maximum-scale=1.0,minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<title>Распределение инвестиций</title>
</head>
<body>

<header class="site-header sticky-top py-1">
<nav class="container d-flex flex-column flex-md-row justify-content-between">
<a class="btn btn-outline-danger" href="/distribution">Распределение инвестиций</a>
    {% if user.is_authenticated %}
<a class="btn btn-outline-danger" href="/distribution/history">Мои результаты</a>
    {% else %}
<a class="btn btn-outline-danger" href="{% url 'signup'%}?next={{request.path}}">Регистрация|Войти</a>
    {% endif %}
</nav>
</header>

{% block body %}{% endblock %}
</body>

{% block edition %}{% endblock %}

<div class="navbar">
<a href="http://math.kubsu.ru"><img src="{% static 'images/fmknn.png' %}" width="27" height="27" alt="Сайт факультета"></a>
<a href="/">Главная</a>
<a href="/faq">FAQ</a>
    {% if user.is_authenticated %}
<a href="{% url 'logout'%}?next={{request.path}}">Выйти</a>
    {% endif %}
</div>

</html>

RaspredInvest/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<h5>{{text.title}}</h5>


<table style="width: 50%;
	margin-bottom: 20px;
	border: 1px solid;
	border-collapse: collapse;">
    <p>Результат:</p>
    <tr>
        {% for header in name_list %}
        <th style="font-weight: bold;
	padding: 5px;
	background: #fffff;
	border: 3px solid #dddddd;">{{header}}</th>
        {% endfor %}
    </tr>
    <tr>
        {% for distribution in distib_list %}
        <td style="border: 3px solid #dddddd;
	padding: 5px;">{{distribution}} y.e.</td>
        {% endfor %}
    </tr>
</table>
<p>Таблица задачи:</p>
<table style="width: 30%;
	margin-bottom: 20px;
	border: 1px solid;
	border-collapse: collapse;">
    {% for row in new_table_list %}
    <tr>
        {% for cell in row %}
        <td style="border: 3px solid #dddddd;
	padding: 5px;">{{cell}}</td>
        {% endfor %}
    </tr>
    {% endfor %}
</table>

<form action="{% url 'appinvest:detail' text.id %}" method="post" enctype="multipart/form-data">
<input type=submit  value="Удалить" name="Удалить" class="btn btn-danger">
</form>
    {% endblock %}

RaspredInvest/templates/faq.html
{% extends 'base.html' %}

{% load static %}

{% block body %}
<h3 align="center">Описание</h3>
<p>Общая постановка задачи о распределении инвестиций следующая: Пусть планируется деятельность нескольких предприятий на очередной промежуток времени. Известно количество начальных средств, которые необходимо так распределить между имеющимися предприятиями в начале промежутка времени, чтобы в конце получить наибольшую прибыль. При этом известна получаемая прибыль от каждого предприятия в зависимости от вложенных в него средств (задана таблично) и выполнены следующие условия: прибыль одного предприятия не зависит от того, сколько средств вложили в другие и суммарная прибыль равна сумме прибылей от каждого предприятия. Прибыль от каждого предприятия выражается в одних и тех же условных денежных единицах.</p>
<p>Данный сайт использует алгоритм динамического программирования Беллмана Ричарда. Динамическое программирование представляет собой математический аппарат, разработанный для эффективного решения некоторого класса задач математического программирования. Этот класс характеризуется возможностью естественного (а иногда и искусственного) разбиения всей операции на ряд взаимосвязанных этапов.</p>
<h3 align="center">Пример</h3>
<p align="center"> <img width="80%" height="100%" src="{% static 'images/primer.png' %}" alt="Картинка примера"></p>
<p>В данной задаче существует 4 предприятия и размер капитала - 120 млн р. Количество капиталовложений 6 с шагом в 20 млн. р. Необходимо выбрать оптимальный план распределения, чтобы получить наибольшую прибыль </p>
<p>Вводим начальные данные и заполняем таблицу</p>
<table align="center">
    <tr>
        <td><p align="center"> <img width="100%" height="50%" src="{% static 'images/prim1.png' %}" alt="Картинка примера"></p></td>
        <td><p align="center"> <img width="100%" height="50%" src="{% static 'images/prim2.png' %}" alt="Картинка примера"></p></td>
    </tr>
    <tr>
       <td><p>Отправляем данные и получаем результат:</p>
           <p align="center"> <img width="80%" height="50%" src="{% static 'images/prim3.png' %}" alt="Картинка примера"></p></td>
       <td><p>Оптимальный план:<br>
           Максимальная прибыль 64 млн р.<br>
           2, 3 и 4 предприятию выделяем 40 млн р.</p>
       </td>
    </tr>
</table>

<h3 align="center">Ограничения</h3>
<p>Максимальное количество предприятий и капиталовложений - 15. Ограничения на размер капитала отсутствуют. Прибыль отдельного предприятия не может быть функцией убывающей.</p>
{% endblock %}
{% block edition %}
<p>_______________________</p>
{% endblock %}

RaspredInvest/templates/gosha.html
false

RaspredInvest/templates/history.html
{% extends 'base.html' %}
{% block body %}
<h2>Ваши результаты:</h2>
{% if latest_text_list %}
{% for a in latest_text_list %}
    <a href="{% url 'appinvest:detail' a.id %}" class="btn btn-large btn-danger" >{{a.title}} </a><br><br>
{% endfor %}
{% else %}
    История пуста
{% endif %}

{% endblock %}

RaspredInvest/templates/mainpage.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
{% if user.is_authenticated %}
<h3 align="center">Добро пожаловать, {{user.username}}!</h3>
{% else %}
<h3 align="center">Добро пожаловать</h3>
{% endif %}

<p align="center">Данный сервис предназначен для решения задачи оптимального
    распределения инвестиций в онлайн режиме.</p>
<p align="center">Такого рода задачи основаны на функции Ричарда Беллмана, основателя
динамического программирования.</p>
<p align="center">Для использования основного функционала необходимо пройти быструю авторизацию пользователя.<br>
Полученные решения хранятся в истории и при желание их возможно сохранить в Word документ
</p>

<script src="{% static 'js/jquery.js' %}"></script>
{% endblock %}

RaspredInvest/templates/temp.html
<html>
<head>
<title>copy to clipboard</title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>
<body>
<input type="text" id="data">
<button type="button" id="copy">Copy</button>
<script>
$(document).ready(function(){
$("#copy").click(function(){
$("#data").select();
document.execCommand("copy");
alert("Copied On clipboard");
});
});
</script>
</body>
</html>